#!/bin/sh

LAN=eth0
INET=eth1

iptables -F
iptables -F -t nat

# iptables -X

# NAT
iptables -t nat -A POSTROUTING -o $INET -j MASQUERADE

# SMTP forwarding to mail server
iptables -t nat -A PREROUTING -p tcp -d 2.3.1.5 --dport 25 -j DNAT --to 10.0.0.2:25

# NAT Loopback
iptables -t nat -A PREROUTING -i $LAN -s 10.0.0.0/8 -d 2.3.1.5/32 -p tcp -m tcp --dport 25 -j DNAT --to 10.0.0.2
iptables -t nat -A POSTROUTING -o $LAN -s 10.0.0.0/8 -d 10.0.0.2/32 -p tcp -m tcp --dport 25 -j SNAT --to 10.0.0.1
